version: '2'
services:
    php-apache:
        image: php:${PHP_VERSION}-apache
        command: bash -c "echo \"${PHP_OVERRIDE_STRING}\" | base64 --decode>${PHP_OVERRIDE_PATH}; apache2-foreground"
        ports:
            - ${WEB_PORT}:80
        volumes:
            - ${WEB_PATH}:/var/www/html
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:${MYSQL_VERSION}
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 0
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${ADMIN_PORT}:80
        links:
            # for mysql container
            - mariadb:db
volumes:
    mariadb:
